import { expandPos } from '../lib/csv-util.js';

function rows(cefr, unit, list) {
  return list.map(([lemma, translation, pos, example, translate]) => ({
    cefr, unit, lemma, translation, pos: expandPos(pos), example: example || '', translate: translate || '',
  }));
}

export function englishB2() {
  return [
    ...rows('B2', 'FILE1', [
      ['identity', 'личность, идентичность', 'N'], ['background', 'происхождение', 'N'],
      ['upbringing', 'воспитание', 'N'], ['roots', 'корни', 'N'], ['heritage', 'наследие', 'N'],
      ['generation', 'поколение', 'N'], ['stereotype', 'стереотип', 'N'],
      ['prejudice', 'предрассудок', 'N'], ['discrimination', 'дискриминация', 'N'],
      ['diversity', 'разнообразие', 'N'], ['inclusion', 'инклюзия', 'N'],
      ['belong', 'принадлежать, чувствовать себя своим', 'V'],
      ['fit in', 'вписываться', 'V'], ['stand out', 'выделяться', 'V'],
      ['take after', 'быть похожим на', 'V'], ['look up to', 'равняться на', 'V'],
      ['look down on', 'смотреть свысока', 'V'], ['come across as', 'производить впечатление', 'V'],
      ['outgoing', 'открытый', 'A'], ['reserved', 'сдержанный', 'A'],
      ['open-minded', 'широких взглядов', 'A'], ['narrow-minded', 'ограниченный', 'A'],
      ['self-aware', 'осознающий себя', 'A'], ['insecure', 'неуверенный', 'A'],
      ['assertive', 'настойчивый', 'A'], ['humble', 'скромный', 'A'],
      ['first impression', 'первое впечатление', 'N'], ['sense of humour', 'чувство юмора', 'N'],
    ]),
    ...rows('B2', 'FILE2', [
      ['work-life balance', 'баланс жизни и работы', 'N'], ['overtime', 'сверхурочка', 'N'],
      ['burnout', 'выгорание', 'N'], ['perk', 'льгота', 'N'], ['bonus', 'премия', 'N'],
      ['commission', 'комиссия, процент', 'N'], ['sick leave', 'больничный', 'N'],
      ['maternity leave', 'декрет', 'N'], ['notice period', 'срок уведомления', 'N'],
      ['redundancy', 'сокращение штата', 'N'], ['resignation', 'увольнение по собственному', 'N'],
      ['workplace', 'рабочее место', 'N'], ['hierarchy', 'иерархия', 'N'],
      ['deadline', 'срок', 'N'], ['target', 'цель, план', 'N'],
      ['delegate', 'делегировать', 'V'], ['supervise', 'контролировать', 'V'],
      ['collaborate', 'сотрудничать', 'V'], ['negotiate', 'вести переговоры', 'V'],
      ['commute', 'ехать на работу', 'V'], ['clock in', 'отмечать приход', 'V'],
      ['demanding', 'требовательный', 'A'], ['tedious', 'утомительный', 'A'],
      ['fulfilling', 'приносящий удовлетворение', 'A'], ['dead-end', 'без перспективы', 'A'],
      ['high-powered', 'высокопоставленный', 'A'], ['white-collar', 'офисный', 'A'],
      ['blue-collar', 'рабочий', 'A'], ['gig economy', 'гиг-экономика', 'N'],
    ]),
    ...rows('B2', 'FILE3', [
      ['consumer', 'потребитель', 'N'], ['consumption', 'потребление', 'N'],
      ['retail', 'розница', 'N'], ['wholesale', 'опт', 'N'], ['e-commerce', 'электронная коммерция', 'N'],
      ['loyalty card', 'карта лояльности', 'N'], ['impulse buy', 'импульсная покупка', 'N'],
      ['window shopping', 'разглядывание витрин', 'N'], ['bestseller', 'бестселлер', 'N'],
      ['counterfeit', 'подделка', 'N'], ['warranty', 'гарантия', 'N'],
      ['complaint', 'жалоба', 'N'], ['refund', 'возврат', 'N'],
      ['bargain', 'торговаться', 'V'], ['haggle', 'торговаться', 'V'],
      ['splurge', 'транжирить', 'V'], ['cut back', 'сокращать траты', 'V'],
      ['rip off', 'обдирать', 'V'], ['shop around', 'сравнивать цены', 'V'],
      ['overpriced', 'завышенный по цене', 'A'], ['good value', 'выгодный', 'A'],
      ['luxurious', 'роскошный', 'A'], ['ethical', 'этичный', 'A'],
      ['fast fashion', 'быстрая мода', 'N'], ['second-hand', 'секонд-хенд', 'A'],
      ['brand-conscious', 'одержимый брендами', 'A'], ['status symbol', 'символ статуса', 'N'],
    ]),
    ...rows('B2', 'FILE4', [
      ['issue', 'проблема, вопрос', 'N'], ['controversy', 'спор, полемика', 'N'],
      ['debate', 'дебаты', 'N'], ['argument', 'аргумент, спор', 'N'],
      ['evidence', 'доказательства', 'N'], ['claim', 'утверждение', 'N'],
      ['opinion', 'мнение', 'N'], ['point of view', 'точка зрения', 'N'],
      ['pros and cons', 'плюсы и минусы', 'N'], ['trade-off', 'компромисс', 'N'],
      ['raise', 'поднимать (вопрос)', 'V'], ['address', 'рассматривать, решать', 'V'],
      ['tackle', 'браться за проблему', 'V'], ['overlook', 'упускать', 'V'],
      ['exaggerate', 'преувеличивать', 'V'], ['underestimate', 'недооценивать', 'V'],
      ['justify', 'оправдывать', 'V'], ['object to', 'возражать против', 'V'],
      ['in favour of', 'за', 'F'], ['against', 'против', 'C'],
      ['as far as I am concerned', 'что касается меня', 'F'],
      ['to a certain extent', 'в определённой степени', 'F'],
      ['on the one hand', 'с одной стороны', 'F'], ['on the other hand', 'с другой стороны', 'F'],
      ['controversial', 'спорный', 'A'], ['convincing', 'убедительный', 'A'],
      ['biased', 'предвзятый', 'A'], ['objective', 'объективный', 'A'],
    ]),
    ...rows('B2', 'FILE5', [
      ['body', 'тело', 'N'], ['posture', 'осанка', 'N'], ['gesture', 'жест', 'N'],
      ['facial expression', 'выражение лица', 'N'], ['eye contact', 'зрительный контакт', 'N'],
      ['handshake', 'рукопожатие', 'N'], ['personal space', 'личное пространство', 'N'],
      ['body language', 'язык тела', 'N'], ['tone of voice', 'тон голоса', 'N'],
      ['shrug', 'пожимать плечами', 'V'], ['nod', 'кивать', 'V'], ['frown', 'хмуриться', 'V'],
      ['yawn', 'зевать', 'V'], ['blush', 'краснеть', 'V'], ['stare', 'пристально смотреть', 'V'],
      ['glance', 'взглянуть', 'V'], ['whisper', 'шептать', 'V'], ['shout', 'кричать', 'V'],
      ['interrupt', 'перебивать', 'V'], ['get the wrong end of the stick', 'неправильно понять', 'F'],
      ['break the ice', 'снять напряжение', 'F'], ['small talk', 'светская беседа', 'N'],
      ['awkward', 'неловкий', 'A'], ['spontaneous', 'спонтанный', 'A'],
      ['tactful', 'тактичный', 'A'], ['blunt', 'прямолинейный', 'A'],
    ]),
    ...rows('B2', 'FILE6', [
      ['science', 'наука', 'N'], ['experiment', 'эксперимент', 'N'],
      ['theory', 'теория', 'N'], ['hypothesis', 'гипотеза', 'N'],
      ['evidence', 'данные, доказательства', 'N'], ['lab', 'лаборатория', 'N'],
      ['researcher', 'исследователь', 'N'], ['discovery', 'открытие', 'N'],
      ['innovation', 'инновация', 'N'], ['breakthrough', 'прорыв', 'N'],
      ['side effect', 'побочный эффект', 'N'], ['vaccine', 'вакцина', 'N'],
      ['gene', 'ген', 'N'], ['DNA', 'ДНК', 'N'], ['clone', 'клон', 'N'],
      ['prove', 'доказывать', 'V'], ['disprove', 'опровергать', 'V'],
      ['analyse', 'анализировать', 'V'], ['measure', 'измерять', 'V'],
      ['observe', 'наблюдать', 'V'], ['conclude', 'делать вывод', 'V'],
      ['carry out', 'проводить', 'V'], ['come up with', 'придумывать', 'V'],
      ['accurate', 'точный', 'A'], ['reliable', 'надёжный', 'A'],
      ['groundbreaking', 'новаторский', 'A'], ['controversial', 'спорный', 'A'],
      ['ethical dilemma', 'этическая дилемма', 'N'], ['peer review', 'рецензирование', 'N'],
    ]),
    ...rows('B2', 'FILE7', [
      ['art', 'искусство', 'N'], ['painting', 'картина, живопись', 'N'],
      ['sculpture', 'скульптура', 'N'], ['exhibition', 'выставка', 'N'],
      ['gallery', 'галерея', 'N'], ['masterpiece', 'шедевр', 'N'],
      ['audience', 'аудитория, публика', 'N'], ['performance', 'выступление', 'N'],
      ['rehearsal', 'репетиция', 'N'], ['stage', 'сцена', 'N'],
      ['plot', 'сюжет', 'N'], ['character', 'персонаж', 'N'],
      ['novel', 'роман', 'N'], ['poetry', 'поэзия', 'N'], ['lyrics', 'текст песни', 'N'],
      ['compose', 'сочинять', 'V'], ['perform', 'исполнять', 'V'],
      ['portray', 'изображать', 'V'], ['depict', 'изображать', 'V'],
      ['inspire', 'вдохновлять', 'V'], ['appreciate', 'ценить', 'V'],
      ['abstract', 'абстрактный', 'A'], ['realistic', 'реалистичный', 'A'],
      ['moving', 'трогательный', 'A'], ['thought-provoking', 'наводящий на размышления', 'A'],
      ['overrated', 'переоценённый', 'A'], ['underrated', 'недооценённый', 'A'],
      ['box office', 'кассовые сборы', 'N'], ['soundtrack', 'саундтрек', 'N'],
    ]),
    ...rows('B2', 'FILE8', [
      ['weather extreme', 'экстремальная погода', 'N'], ['hurricane', 'ураган', 'N'],
      ['tornado', 'торнадо', 'N'], ['earthquake', 'землетрясение', 'N'],
      ['tsunami', 'цунами', 'N'], ['wildfire', 'лесной пожар', 'N'],
      ['avalanche', 'лавина', 'N'], ['landslide', 'оползень', 'N'],
      ['famine', 'голод', 'N'], ['outbreak', 'вспышка (болезни)', 'N'],
      ['evacuate', 'эвакуировать', 'V'], ['rescue', 'спасать', 'V'],
      ['survive', 'выживать', 'V'], ['rebuild', 'восстанавливать', 'V'],
      ['donate', 'жертвовать', 'V'], ['volunteer', 'работать волонтёром', 'V'],
      ['warn', 'предупреждать', 'V'], ['forecast', 'прогнозировать', 'V'],
      ['devastating', 'разрушительный', 'A'], ['severe', 'сильный, суровый', 'A'],
      ['mild', 'мягкий', 'A'], ['unpredictable', 'непредсказуемый', 'A'],
      ['natural disaster', 'стихийное бедствие', 'N'], ['aid', 'помощь', 'N'],
      ['shelter', 'убежище', 'N'], ['casualty', 'пострадавший', 'N'],
    ]),
    ...rows('B2', 'FILE9', [
      ['law', 'закон', 'N'], ['right', 'право', 'N'], ['duty', 'обязанность', 'N'],
      ['citizen', 'гражданин', 'N'], ['government', 'правительство', 'N'],
      ['election', 'выборы', 'N'], ['vote', 'голос, голосовать', 'N'],
      ['campaign', 'кампания', 'N'], ['policy', 'политика (курс)', 'N'],
      ['protest', 'протест', 'N'], ['petition', 'петиция', 'N'],
      ['freedom of speech', 'свобода слова', 'N'], ['human rights', 'права человека', 'N'],
      ['ban', 'запрещать', 'V'], ['legalise', 'легализовать', 'V'],
      ['enforce', 'обеспечивать соблюдение', 'V'], ['abolish', 'отменять, упразднять', 'V'],
      ['elect', 'избирать', 'V'], ['demonstrate', 'демонстрировать, митинговать', 'V'],
      ['fair', 'справедливый', 'A'], ['unfair', 'несправедливый', 'A'],
      ['democratic', 'демократический', 'A'], ['corrupt', 'коррумпированный', 'A'],
      ['civil', 'гражданский', 'A'], ['public opinion', 'общественное мнение', 'N'],
    ]),
    ...rows('B2', 'FILE10', [
      ['food industry', 'пищевая промышленность', 'N'], ['supply chain', 'цепочка поставок', 'N'],
      ['organic farming', 'органическое земледелие', 'N'], ['pesticide', 'пестицид', 'N'],
      ['additives', 'добавки', 'N'], ['preservative', 'консервант', 'N'],
      ['nutrition', 'питание', 'N'], ['calorie', 'калория', 'N'],
      ['protein', 'белок', 'N'], ['carbohydrate', 'углевод', 'N'],
      ['obesity', 'ожирение', 'N'], ['malnutrition', 'недоедание', 'N'],
      ['food waste', 'пищевые отходы', 'N'], ['food miles', 'продовольственные мили', 'N'],
      ['harvest', 'урожай, собирать урожай', 'N'], ['crop', 'сельхозкультура', 'N'],
      ['livestock', 'скот', 'N'], ['seafood', 'морепродукты', 'N'],
      ['craving', 'тяга (к еде)', 'N'], ['appetite', 'аппетит', 'N'],
      ['digest', 'переваривать', 'V'], ['skip a meal', 'пропускать приём пищи', 'V'],
      ['put on weight', 'набирать вес', 'V'], ['lose weight', 'худеть', 'V'],
      ['nutritious', 'питательный', 'A'], ['bland', 'пресный', 'A'],
      ['rich', 'сытный, насыщенный', 'A'], ['raw', 'сырой', 'A'],
    ]),
    ...rows('B2', 'FILE11', [
      ['memory', 'память', 'N'], ['concentration', 'концентрация', 'N'],
      ['intelligence', 'интеллект', 'N'], ['creativity', 'креативность', 'N'],
      ['instinct', 'инстинкт', 'N'], ['intuition', 'интуиция', 'N'],
      ['emotion', 'эмоция', 'N'], ['mood', 'настроение', 'N'],
      ['anxiety', 'тревога', 'N'], ['depression', 'депрессия', 'N'],
      ['self-esteem', 'самооценка', 'N'], ['motivation', 'мотивация', 'N'],
      ['recall', 'вспоминать', 'V'], ['remind', 'напоминать', 'V'],
      ['distract', 'отвлекать', 'V'], ['focus', 'фокусироваться', 'V'],
      ['cope with', 'справляться с', 'V'], ['bottle up', 'сдерживать (чувства)', 'V'],
      ['cheer up', 'подбодрить', 'V'], ['calm down', 'успокаиваться', 'V'],
      ['absent-minded', 'рассеянный', 'A'], ['sharp', 'острый умом', 'A'],
      ['gifted', 'одарённый', 'A'], ['overwhelmed', 'перегруженный', 'A'],
      ['mind goes blank', 'ум заходит за разум', 'F'],
      ['learn by heart', 'учить наизусть', 'F'],
    ]),
    ...rows('B2', 'FILE12', [
      ['phrase', 'фраза', 'N'], ['idiom', 'идиома', 'N'], ['collocation', 'коллокация', 'N'],
      ['phrasal verb', 'фразовый глагол', 'N'], ['register', 'регистр речи', 'N'],
      ['slang', 'сленг', 'N'], ['formal', 'официальный', 'A'],
      ['informal', 'неформальный', 'A'], ['literal', 'буквальный', 'A'],
      ['figurative', 'переносный', 'A'], ['nuance', 'нюанс', 'N'],
      ['get across', 'донести мысль', 'V'], ['sum up', 'подводить итог', 'V'],
      ['point out', 'указывать', 'V'], ['bring up', 'поднимать тему', 'V'],
      ['make sense', 'иметь смысл', 'V'], ['miss the point', 'не уловить суть', 'V'],
      ['in other words', 'другими словами', 'F'], ['that is to say', 'то есть', 'F'],
      ['as a matter of fact', 'на самом деле', 'F'], ['by the way', 'кстати', 'F'],
      ['to be honest', 'честно говоря', 'F'], ['needless to say', 'излишне говорить', 'F'],
      ['bear in mind', 'иметь в виду', 'F'], ['take into account', 'принимать во внимание', 'F'],
      ['on second thoughts', 'по зрелом размышлении', 'F'],
      ['the bottom line', 'суть, итог', 'N'],
    ]),
  ];
}
